#!/usr/bin/env bash

DOTFILES=".bash_profile .bashrc .exrc .gdbinit .inputrc .screenrc .tmux.conf .vimrc"
BASEURL="https://raw.githubusercontent.com/emanuelduss/Configs/master/home/"

for dotfile in $DOTFILES
do
  echo "[*] Getting dotfile $HOME/$dotfile"
  wget -q "$BASEURL/$dotfile" -O "$HOME/$dotfile"
done
