#!/usr/bin/env bash

DOTFILES=".bash_profile .bashrc .exrc .gdbinit .gitconfig .inputrc .screenrc .tmux.conf .vimrc"
BASEURL="https://raw.githubusercontent.com/mindfuckup/Configs/master/home/"

for dotfile in $DOTFILES
do
  echo "[*] Getting dotfile $HOME/$dotfile"
  curl -s "$BASEURL/$dotfile" -o "$HOME/$dotfile"
done
