#!/usr/bin/env bash

CONFIGDIR="$HOME/.configs"
DOTFILES=".bash_profile .bashrc .exrc .gdbinit .gitconfig .inputrc .screenrc .tmux.conf .vimrc"

echo "[*] Cloning config repo"
git clone --depth 1 https://github.com/emanuelduss/Configs.git "$CONFIGDIR"

for dotfile in $DOTFILES
do
  echo "[*] Linking dotfile $HOME/$dotfile"
  ln -fs "$CONFIGDIR/home/$dotfile" "$HOME/$dotfile"
done
