#!/usr/bin/env bash

HOME=/tmp/home
CONFIGDIR="$HOME/.configs"
DOTFILES=".bash_profile .bashrc .exrc .gdbinit .gitconfig .inputrc .screenrc .tmux.conf .vimrc"

echo "[*] Cloning config repo"
git clone --depth 1 https://github.com/mindfuckup/Configs.git "$CONFIGDIR"

for dotfile in $DOTFILES
do
  echo "[*] Linking dotfile $HOME/$dotfile"
  ln -s "$CONFIGDIR/home/$dotfile" "$HOME/$dotfile"
done
